### ISSUE TITLE
Hello,无意中看到您github主页介绍中的立体贡献图十分有趣，可以请教下是如何实现的吗

### ISSUE THREAD

**Issue by Jia-Jingnan** [fengwei2002/fengwei2002#1]
Hello,无意中看到您github主页介绍中的立体贡献图十分有趣，可以请教下是如何实现的吗

**Comment by funcdfs** [comment]
这个工具：https://github.com/lowlighter/metrics 和 GitHub action，具体使用去看那个仓库的介绍~
