### ISSUE TITLE
[Comments] JavaScript Kit

### ISSUE THREAD

**Issue by funcdfs** [fengwei2002/fengwei2002#2]
https://konng.vercel.app/posts/2022/05/23/javascriptkit.html

**Comment by funcdfs** [comment]
hello vusse

**Comment by psychonaut1f** [comment]
@fengwei2002

> hello vusse

omg

**Comment by funcdfs** [comment]
@psychonaut1f

> @fengwei2002
> 
> > hello vusse
> 
> omg

hhh
